# baseURL = "https://your_domain.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "NovaCore"
copyright = "All Rights Reserved NovaCore:copyright:2022"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  # name = "Your name here"
  # image = "img/author.jpg"  # path relative to static directory

  links = [
    { link = {href = "https://novacore.info", text = "Website" }},
    { blog-solid = {href = "https://novacore.info/blog", text= "Recent Posts"}},
    { email = "mailto:contact@novacore.info" },
    { facebook = "https://www.facebook.com/NovaCoreSMB" },
    { instagram = "https://instagram.com/novacore_smb" },
    { google = "https://g.page/r/Cesc2iNY-i13EAE" },
    { dribbble = "https://dribbble.com/nova_core" },
    { discord = "https://discord.gg/QwTHSUnv5A" },
    { github = "https://github.com/nova-core-creatives" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },



    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },

    # { gitlab = "https://gitlab.com/username" },


    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
